import LoginPage from "./Pages/Login";
import SignupPage from "./Pages/SignUp";
import Home from "./Pages/Home";
import CreateProduct from "./Pages/createProduct";
import MyProducts from "./Pages/myProducts";
import Cart from "./Pages/cart";
import ProductDetails from "./pages/productDetails.jsx";
import Profile from "./pages/profile.jsx";
import CreateAddress from "./pages/createAddress.jsx";
import SelectAddress from "./pages/SelectAddress.jsx";
import OrderConfirmation from "./pages/OrderConfirmation.jsx";
import MyOrdersPage from "./pages/myorders.jsx";
export {LoginPage, SignupPage, Home, CreateProduct , MyProducts, Cart, ProductDetails , Profile , CreateAddress , SelectAddress , OrderConfirmation , MyOrdersPage};